style(material/api-theme): change api page links color
angular/material.angular.io pull request #993
Opened 2021-05-25 09:20 UTC by kian23kpt

Styles for links on API page was unreadable and don't have sufficient contrast in dark mode so now with change theme links color will change.

Fixes #911

2021-05-25 09:26 UTC, kian23kpt commented
Now API page links color set like as theme color and have sufficient contrast.

![Screenshot (12)](https://user-images.githubusercontent.com/48172978/119473698-aa80a600-bd60-11eb-99c6-caaee801830c.png)
![Screenshot (13)](https://user-images.githubusercontent.com/48172978/119473703-ac4a6980-bd60-11eb-963b-a5b572fcd0fb.png)
![Screenshot (10)](https://user-images.githubusercontent.com/48172978/119473705-ac4a6980-bd60-11eb-8382-0fc9fc3b7485.png)
![Screenshot (11)](https://user-images.githubusercontent.com/48172978/119473707-ace30000-bd60-11eb-9e4a-abc55948abf4.png)

2021-05-26 17:06 UTC, Splaktar reviewed
Thank you for this. Can you please post screenshots for both `a` and `a:visited`?

And rebase this branch on `master`?

2021-05-26 17:06 UTC, Splaktar commented on src/styles/_api-theme.scss
> +  //API docs link color will change with theme change
```suggestion
  // API docs link color will change with theme change
```

2021-05-28 13:51 UTC, kian23kpt commented
> 
> 
> Thank you for this. Can you please post screenshots for both `a` and `a:visited`?
> 
> And rebase this branch on `master`?

I have checked. there is no difference between them.

![Screenshot (11)](https://user-images.githubusercontent.com/48172978/119994016-71a33400-bfe1-11eb-9a2e-1f97681c5883.png)

2021-06-15 22:48 UTC, Splaktar requested changes
> I have checked. there is no difference between them.

We should probably have a slight difference between visited and unvisited links.

That said, it seems like something happened to this PR when you merged `master` into this branch. We don't accept merge commits, so we actually need this to be rebased. However, at this point, I don't see the original changes anymore. So it might be best to create a new branch and PR.

2021-06-15 22:52 UTC, Splaktar commented
It looks like this was resolved in PR https://github.com/angular/material.angular.io/pull/990 by @crisbeto.

2021-06-15 22:52 UTC, closed without merging